CREATE TABLE marca (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE modelo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    marca_id BIGINT NOT NULL REFERENCES marca (id)
);

CREATE TABLE clientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_social VARCHAR(255),
    nome VARCHAR(255),
    tipo_documento VARCHAR(50),
    documento VARCHAR(255) NOT NULL UNIQUE,
    email VARCHAR(255),
    telefone VARCHAR(255),
    contato_whats_app BOOLEAN,
    logradouro VARCHAR(255),
    numero VARCHAR(255),
    complemento VARCHAR(255),
    bairro VARCHAR(255),
    cidade VARCHAR(255),
    uf VARCHAR(255),
    cep VARCHAR(255)
);
CREATE INDEX idx_documento ON clientes (documento);

CREATE TABLE veiculo (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    placa VARCHAR(255) NOT NULL UNIQUE,
    ano INTEGER NOT NULL,
    cor VARCHAR(255) NOT NULL,
    modelo_id BIGINT REFERENCES modelo (id),
    cliente_id BIGINT REFERENCES clientes (id)
);
CREATE INDEX idx_placa ON veiculo (placa);
CREATE INDEX idx_cliente_id ON veiculo (cliente_id);

CREATE TABLE produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    sku VARCHAR(255) NOT NULL UNIQUE,
    ean VARCHAR(255) NOT NULL UNIQUE,
    nome VARCHAR(255),
    preco NUMERIC(19,4),
    estoque INTEGER,
    estoque_reservado INTEGER,
    estoque_minimo INTEGER,
    tipo_produto VARCHAR(50),
    tipo_peca VARCHAR(50),
    tipo_insumo VARCHAR(50),
    quantidade_embalagem NUMERIC(19,4),
    unidade_de_medida VARCHAR(50)
);
CREATE INDEX idx_produto_sku ON produtos (sku);
CREATE INDEX idx_produto_ean ON produtos (ean);
CREATE INDEX idx_produto_tipo_peca ON produtos (tipo_peca);
CREATE INDEX idx_produto_tipo_insumo ON produtos (tipo_insumo);

CREATE TABLE aplicacao_produtos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    produto_id BIGINT REFERENCES produtos (id),
    modelo_id BIGINT REFERENCES modelo (id),
    quantidade INTEGER NOT NULL,
    ano_inicio INTEGER NOT NULL,
    ano_fim INTEGER NOT NULL
);
CREATE INDEX idx_produto_id ON aplicacao_produtos (produto_id);
CREATE INDEX idx_modelo_id ON aplicacao_produtos (modelo_id);

CREATE TABLE servicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL UNIQUE,
    horas_tecnicas NUMERIC(19,4)
);

CREATE TABLE servico_insumos (
    servico_id BIGINT NOT NULL REFERENCES servicos (id),
    tipo_insumo VARCHAR(50),
    PRIMARY KEY (servico_id, tipo_insumo)
);

CREATE TABLE servico_tipo_pecas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_id BIGINT NOT NULL REFERENCES servicos (id),
    tipo_peca VARCHAR(50) NOT NULL,
    quantidade INTEGER NOT NULL
);

CREATE TABLE ordens_de_servico (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status VARCHAR(50) NOT NULL,
    cliente_id BIGINT NOT NULL REFERENCES clientes (id),
    veiculo_id BIGINT NOT NULL REFERENCES veiculo (id),
    complexidade VARCHAR(50),
    sintomas TEXT,
    tag_chave VARCHAR(255) UNIQUE,
    preco_total NUMERIC(19,4),
    preco_servicos_desejados NUMERIC(19,4),
    preco_servicos_necessarios NUMERIC(19,4),
    preco_servicos_adicionais NUMERIC(19,4),
    justificativa_necessarios TEXT,
    justificativa_adicionais TEXT,
    created_at TIMESTAMP NOT NULL
);
CREATE INDEX idx_os_status ON ordens_de_servico (status);
CREATE INDEX idx_os_cliente_id ON ordens_de_servico (cliente_id);
CREATE INDEX idx_os_veiculo_id ON ordens_de_servico (veiculo_id);
CREATE INDEX idx_os_tag_chave ON ordens_de_servico (tag_chave);

CREATE TABLE status_changes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_de_servico_id BIGINT NOT NULL REFERENCES ordens_de_servico (id),
    status VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE servico_os (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    ordem_de_servico_id BIGINT NOT NULL REFERENCES ordens_de_servico (id),
    servico_id BIGINT NOT NULL REFERENCES servicos (id),
    tipo VARCHAR(50) NOT NULL,
    aprovado BOOLEAN,
    preco_total NUMERIC(19,4),
    preco_horas_tecnicas NUMERIC(19,4)
);

CREATE TABLE peca_os (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_os_id BIGINT NOT NULL REFERENCES servico_os (id),
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    quantidade INTEGER NOT NULL,
    preco_total NUMERIC(19,4) NOT NULL,
    reservado BOOLEAN NOT NULL DEFAULT FALSE
);

CREATE TABLE insumo_os (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    servico_os_id BIGINT NOT NULL REFERENCES servico_os (id),
    produto_id BIGINT NOT NULL REFERENCES produtos (id),
    quantidade INTEGER NOT NULL,
    preco_total NUMERIC(19,4) NOT NULL,
    reservado BOOLEAN NOT NULL DEFAULT FALSE
);
