apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-config
  namespace: tech-challenge
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "docker"
  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "dev@local"
  MAIL_SMTP_AUTH: "false"
  MAIL_SMTP_STARTTLS: "false"
  APPROVAL_TTL_MINUTES: "1440"
  APP_BASE_URL: "${APP_BASE_URL}"
  JWT_JWK_SET_URI: "${JWT_JWK_SET_URI}"
  JWT_ISSUER: "g52-lambda-auth"
  JWT_AUDIENCE: "tech-challenge-api"
  DB_HOST: "${DB_HOST}"
  DB_PORT: "${DB_PORT}"
  DB_NAME: "${DB_NAME}"
  DB_USERNAME: "${DB_USERNAME}"