apiVersion: v1
kind: ConfigMap
metadata:
  name: tech-challenge-config
  namespace: tech-challenge
data:
  SERVER_PORT: "8080"
  SPRING_PROFILES_ACTIVE: "docker"
  MAIL_HOST: "mailpit"
  MAIL_PORT: "1025"
  MAIL_USERNAME: "dev@local"
  MAIL_SMTP_AUTH: "false"
  MAIL_SMTP_STARTTLS: "false"
  APPROVAL_TTL_MINUTES: "1440"
  APP_BASE_URL: "${APP_BASE_URL}"
  KEYCLOAK_JWK_SET_URI: "http://keycloak:9000/realms/g52/protocol/openid-connect/certs"
  KEYCLOAK_ADMIN: "admin"
  KC_HTTP_PORT: "9000"
  DB_HOST: "postgres"
  DB_PORT: "5432"
  DB_NAME: "techchallenge"
  DB_USERNAME: "techchallenge"