apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  namespace: tech-challenge
  labels:
    app: keycloak
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      containers:
        - name: keycloak
          image: "${KEYCLOAK_IMAGE}"
          ports:
            - containerPort: 9000
          env:
            - name: KEYCLOAK_ADMIN
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: KEYCLOAK_ADMIN
            - name: KEYCLOAK_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: KEYCLOAK_ADMIN_PASSWORD
            - name: KC_HTTP_PORT
              valueFrom:
                configMapKeyRef:
                  name: tech-challenge-config
                  key: KC_HTTP_PORT
            - name: KEYCLOAK_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: KEYCLOAK_CLIENT_ID
            - name: KEYCLOAK_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: tech-challenge-secrets
                  key: KEYCLOAK_CLIENT_SECRET
          readinessProbe:
            tcpSocket:
              port: 9000
            initialDelaySeconds: 30
            periodSeconds: 10
            failureThreshold: 10
          resources:
            requests:
              cpu: "150m"
              memory: "350Mi"
            limits:
              cpu: "400m"
              memory: "600Mi"
---
apiVersion: v1
kind: Service
metadata:
  name: keycloak
  namespace: tech-challenge
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: "external"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: "ip"
    service.beta.kubernetes.io/aws-load-balancer-scheme: "internet-facing"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-protocol: "TCP"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-interval: "15"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-healthy-threshold: "2"
    service.beta.kubernetes.io/aws-load-balancer-healthcheck-unhealthy-threshold: "3"
spec:
  type: LoadBalancer
  selector:
    app: keycloak
  ports:
    - name: keycloak
      port: 9000
      targetPort: 9000
      protocol: TCP
