apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge
type: Opaque
stringData:
  MAIL_PASSWORD: "${MAIL_PASSWORD}"
  APPROVAL_SECRET: "${APPROVAL_SECRET}"
  KEYCLOAK_ADMIN_PASSWORD: "${KEYCLOAK_ADMIN_PASSWORD}"