apiVersion: v1
kind: Secret
metadata:
  name: tech-challenge-secrets
  namespace: tech-challenge
type: Opaque
stringData:
  MAIL_PASSWORD: "${MAIL_PASSWORD}"
  APPROVAL_SECRET: "${APPROVAL_SECRET}"
  DB_PASSWORD: "${DB_PASSWORD}"