server:
  port: ${SERVER_PORT:8080}

spring:
  application:
    name: tech-challenge-ms

management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, metrics
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
    metrics:
      enabled: true
  metrics:
    export:
      prometheus:
        enabled: true

logging:
  level:
    root: info