package com.grupo52.tech_challenge.domain.Enums;

public enum TipoPeca {
    // Filtros
    FILTRO_OLEO,
    FILTRO_AR,
    FILTRO_COMBUSTIVEL,
    FILTRO_CABINE,

    // Freios
    PASTILHA_FREIO,
    DISCO_FREIO,
    SAPATA_FREIO,
    TAMBOR_FREIO,
    CILINDRO_MESTRE,
    SERVO_FREIO,

    // Iluminação
    FAROL_DIREITO,
    FAROL_ESQUERDO,
    LANTERNA_DIREITA,
    LANTERNA_ESQUERDA,
    LAMPADA_LUZ_ALTA,
    LAMPADA_LUZ_BAIXA,
    LAMPADA_FREIO,
    LAMPADA_SETA,
    LAMPADA_RE,
    FAROL_MILHA,

    // Ignição
    VELA_IGNICAO,
    CABO_VELA,
    BOBINA_IGNICAO,

    // Elétrica
    BATERIA,
    ALTERNADOR,
    MOTOR_PARTIDA,
    FUSIVEL,
    RELE,

    // Suspensão
    AMORTECEDOR_DIANTEIRO,
    AMORTECEDOR_TRASEIRO,
    MOLA_DIANTEIRA,
    MOLA_TRASEIRA,
    BANDEJA_SUSPENSAO,
    BIELETA,
    PIVO_SUSPENSAO,
    BUCHA_BANDEJA,

    // Direção
    TERMINAL_DIRECAO,
    AXIAL_DIRECAO,
    CAIXA_DIRECAO,
    BOMBA_DIRECAO,

    // Motor
    JUNTA_CABECOTE,
    RETENTOR,
    COXIM_MOTOR,
    CORREIA_DENTADA,
    CORREIA_ALTERNADOR,
    TENSOR_CORREIA,

    // Arrefecimento
    RADIADOR,
    BOMBA_DAGUA,
    VALVULA_TERMOSTATICA,
    VENTOINHA,
    RESERVATORIO_EXPANSAO,

    // Transmissão
    KIT_EMBREAGEM,
    DISCO_EMBREAGEM,
    PLATO_EMBREAGEM,
    ROLAMENTO_EMBREAGEM,
    HOMOCINETICA,

    // Limpeza
    PALHETA_LIMPADOR,
    MOTOR_LIMPADOR,
    RESERVATORIO_PARABRISA,

    // Rodas
    PNEU,
    RODA,
    CALOTA,

    // Carroceria
    PARACHOQUE_DIANTEIRO,
    PARACHOQUE_TRASEIRO,
    CAPO,
    PORTA,
    TETO,
    PARA_LAMA_DIREITO,
    PARA_LAMA_ESQUERDO,
    RETROVISOR_DIREITO,
    RETROVISOR_ESQUERDO
}
